# Workflow For Continous Integration for ouir react native web app.
name: CI For React Native

on:
  # For Main Branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # Runs on latest Ubuntu
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # Run build for both Node version 16
        node-version: [16.x]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # installing Node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
        # this is regarding the matrix strategy specified above
          node-version: ${{ matrix.node-version }}
      # Allow peer dependencies for React Native Navigation
      - run: npm config set legacy-peer-deps true
      # install dependencies
      - run: npm ci
      # Run ESlint
      - run: npm run lint
      # build the project if necessary
      - run: npm run build --if-present
      # run tests
      - run: npm test
      # run coverage
      - run: npm run coverage
